#include "CameraRigBA.h"

#include <boost/unordered_set.hpp>
#include <glibmm.h>
#include <opencv2/core/eigen.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>

#include "../../external/ceres-solver/include/ceres/ceres.h"
#include "../../library/bundle_adj/ReprojectionError.h"
#include "../../library/bundle_adj/SlidingWindowBA.h"
#include "../../library/gpl/CameraEnums.h"
#include "../../library/gpl/EigenUtils.h"
#include "../../library/npoint/five-point/five-point.hpp"
#include "../../mapping/feature_tracker/SurfGPU.h"
#include "../../visualization/overlay/GLOverlayExtended.h"

namespace camodocal
{

CameraRigBA::CameraRigBA(const std::vector<CataCameraParameters>& cameraParameters,
                         SparseGraph& graph,
                         CameraRigExtrinsics& extrinsics)
 : mExtrinsics(extrinsics)
 , mGraph(graph)
 , kLocalMapWindowDistance(3.0)
 , kMaxDistanceRatio(0.7f)
 , kMaxPoint3DDistance(20.0)
 , kMaxReprojErr(2.0)
 , kMinLoopCorrespondences2D2D(80)
 , kMinInterCorrespondences2D2D(15)
 , kNearestImageMatches(15)
 , kNominalFocalLength(300.0)
 , mVerbose(false)
{
    for (size_t i = 0; i < cameraParameters.size(); ++i)
    {
        mCameras.push_back(new CataCamera(cameraParameters.at(i)));
        mCameraCalibs.push_back(new CataCameraCalibration("", cv::Size(cameraParameters.at(i).imageWidth(), cameraParameters.at(i).imageHeight())));
        mCameraParameters.push_back(cameraParameters.at(i));

        mCameraCalibs.back()->cameraParameters() = mCameraParameters.back();
    }
}

void
CameraRigBA::run(int beginStage, bool findLoopClosures, bool saveWorkingData, std::string dataDir)
{
    // stage 1 - triangulate 3D points with feature correspondences from mono VO and run BA
    // stage 2 - find local inter-camera 3D-3D correspondences and run BA
    // stage 3 - find loop closures and run BA

    if (mVerbose)
    {
        for (size_t i = 0; i < mCameras.size(); ++i)
        {
            std::cout << "# INFO: Camera " << i << ":" << std::endl;
            std::cout << "# INFO:   # segments = " << mGraph.frameSegments(i).size() << std::endl;
            for (size_t j = 0; j < mGraph.frameSegments(i).size(); ++j)
            {
                FrameSegment& segment = mGraph.frameSegments(i).at(j);

                std::cout << "# INFO:   Segment " << j << ": # frames = " << segment.size() << std::endl;
            }
        }
    }

    for (size_t i = 0; i < mCameras.size(); ++i)
    {
        for (size_t j = 0; j < mGraph.frameSegments(i).size(); ++j)
        {
            FrameSegment& segment = mGraph.frameSegments(i).at(j);

            for (size_t k = 0; k < segment.size(); ++k)
            {
                FramePtr& frame = segment.at(k);

                frame->cameraId() = i;
            }
        }
    }

    // visualize graph produced by previous stage
    if (beginStage == 1)
    {
        visualize("unopt-", ODOMETER);
        visualizeExtrinsics("unopt-extrinsics");
    }
    if (beginStage == 2)
    {
        visualize("opt1-BA-", ODOMETER);
        visualizeExtrinsics("opt1-extrinsics");
    }
    else if (beginStage == 3)
    {
        visualize("opt2-BA-", ODOMETER);
        visualizeExtrinsics("opt2-extrinsics");
    }
    else if (beginStage > 3)
    {
        visualize("opt3-BA-", ODOMETER);
        visualizeExtrinsics("opt3-extrinsics");
    }

//    mExtrinsics.readFromFile("../config/calib/calib_camera_kermit/2012_09_03/extrinsic.txt");
//    visualizeExtrinsics("ref-extrinsics");

    // stage 1
    if (beginStage <= 1)
    {
        prune(PRUNE_BEHIND_CAMERA, CAMERA);

        if (mVerbose)
        {
            std::cout << "# INFO: Triangulating feature correspondences... " << std::endl;
        }

        // remove 3D points generated by monocular VO
        for (size_t i = 0; i < mCameras.size(); ++i)
        {
            for (size_t j = 0; j < mGraph.frameSegments(i).size(); ++j)
            {
                FrameSegment& segment = mGraph.frameSegments(i).at(j);

                for (size_t k = 0; k < segment.size(); ++k)
                {
                    FramePtr& frame = segment.at(k);

                    std::vector<Point2DFeaturePtr>& features2D = frame->features2D();

                    for (size_t l = 0; l < features2D.size(); ++l)
                    {
                        Point2DFeaturePtr& pf = features2D.at(l);

                        if (pf->feature3D().get() != 0)
                        {
                            pf->feature3D() = Point3DFeaturePtr();
                        }
                    }

                    frame->features3D().clear();
                }
            }
        }

        // triangulate feature correspondences to get 3D scene points in odometry frame
        for (size_t i = 0; i < mCameras.size(); ++i)
        {
            Pose T_cam_odo(mExtrinsics.getGlobalCameraPose(i));

            for (size_t j = 0; j < mGraph.frameSegments(i).size(); ++j)
            {
                FrameSegment& segment = mGraph.frameSegments(i).at(j);

                if (segment.size() < 3)
                {
                    continue;
                }

                for (size_t k = 2; k < segment.size(); ++k)
                {
                    triangulateFeatures(segment.at(k-2), segment.at(k-1), segment.at(k),
                                        *(mCameras.at(i)), mCameraParameters.at(i), T_cam_odo);
                }
            }
        }

        if (!validateGraph())
        {
            std::cout << "# ERROR: Graph is not valid." << std::endl;
            exit(1);
        }

        prune(PRUNE_BEHIND_CAMERA, ODOMETER);

        double minError, maxError, avgError;
        size_t featureCount;

        reprojectionError(minError, maxError, avgError, featureCount, ODOMETER);

        if (mVerbose)
        {
            std::cout << "# INFO: Reprojection error after triangulation: avg = " << avgError
                      << " px | max = " << maxError << " px | count = " << featureCount << std::endl;
        }

        visualize("unopt-", ODOMETER);

        if (mVerbose)
        {
            std::cout << "# INFO: Running BA on odometer data... " << std::endl;
        }

        // optimize camera extrinsics and 3D scene points
        optimize(ODOMETER_FIXED, false);

        prune(PRUNE_BEHIND_CAMERA); // | PRUNE_FARAWAY | PRUNE_HIGH_REPROJ_ERR, ODOMETER);

        reprojectionError(minError, maxError, avgError, featureCount, ODOMETER);

        if (mVerbose)
        {
            std::cout << "# INFO: Done." << std::endl;
            std::cout << "# INFO: Reprojection error after BA (odometer): avg = " << avgError
                      << " px | max = " << maxError << " px | count = " << featureCount << std::endl;
        }

        visualize("opt1-BA-", ODOMETER);

        visualizeExtrinsics("opt1-extrinsics");

        if (saveWorkingData)
        {
            boost::filesystem::path extrinsicPath(dataDir);
            extrinsicPath /= "tmp_extrinsic_1.txt";
            mExtrinsics.writeToFile(extrinsicPath.string());

            boost::filesystem::path graphPath(dataDir);
            graphPath /= "frames_1.sg";
            mGraph.writeToBinaryFile(graphPath.string());
        }
    }

    // stage 2
    if (beginStage <= 2)
    {
        if (mVerbose)
        {
            std::cout << "# INFO: Finding inter-map 3D-3D correspondences... " << std::endl;
        }

        prune(PRUNE_BEHIND_CAMERA);

        // find local inter-map 3D-3D correspondences
        std::vector<Correspondence2D2D> localInterMap2D2D;
        findLocalInterMap2D2DCorrespondences(localInterMap2D2D);

        if (mVerbose)
        {
            std::cout << "# INFO: # local inter-map 3D-3D correspondences = "
                      << localInterMap2D2D.size() << std::endl;

            size_t featureCount[CAMERA_COUNT];
            for (int i = 0; i < CAMERA_COUNT; ++i)
            {
                featureCount[i] = 0;
            }

            for (size_t i = 0; i < localInterMap2D2D.size(); ++i)
            {
                ++featureCount[localInterMap2D2D.at(i).first->frame()->cameraId()];
                ++featureCount[localInterMap2D2D.at(i).second->frame()->cameraId()];
            }

            for (int i = 0; i < CAMERA_COUNT; ++i)
            {
                std::cout << "# INFO: # features seen in camera " << i
                          << ": " << featureCount[i] << std::endl;
            }
        }

        std::vector<boost::tuple<int, int, FramePtr, FramePtr> > localInterMapFrameFrame;
        for (size_t i = 0; i < localInterMap2D2D.size(); ++i)
        {
            FramePtr& f1 = localInterMap2D2D.at(i).first->frame();
            FramePtr& f2 = localInterMap2D2D.at(i).second->frame();

            localInterMapFrameFrame.push_back(boost::make_tuple(f1->cameraId(), f2->cameraId(), f1, f2));
        }

        visualizeFrameFrameCorrespondences("local-inter-p-p", localInterMapFrameFrame);
        visualize3D3DCorrespondences("local-inter-3d-3d", localInterMap2D2D);

        for (size_t i = 0; i < localInterMap2D2D.size(); ++i)
        {
            Point3DFeaturePtr p1 = localInterMap2D2D.at(i).first->feature3D();
            Point3DFeaturePtr p2 = localInterMap2D2D.at(i).second->feature3D();

            p2->features2D().insert(p2->features2D().end(), p1->features2D().begin(), p1->features2D().end());
            std::sort(p2->features2D().begin(), p2->features2D().end());
            p2->features2D().erase(std::unique(p2->features2D().begin(), p2->features2D().end()), p2->features2D().end());

            std::vector<Point2DFeaturePtr> features2D = p2->features2D();
            for (size_t j = 0; j < features2D.size(); ++j)
            {
                features2D.at(j)->feature3D() = p2;
            }
        }

        prune(PRUNE_BEHIND_CAMERA);

        double minError, maxError, avgError;
        size_t featureCount;

        reprojectionError(minError, maxError, avgError, featureCount, ODOMETER);

        if (mVerbose)
        {
            std::cout << "# INFO: Done." << std::endl;
            std::cout << "# INFO: Reprojection error with points seen in at least 2 cameras: avg = " << avgError
                      << " px | max = " << maxError << " px | count = " << featureCount << std::endl;
        }

        if (!findLoopClosures)
        {
            std::cout << "# INFO: Running BA on odometer data..." << std::endl;

            // perform BA to optimize intrinsics, extrinsics, odometry poses, and scene points
            optimize(CATA_ODOMETER, true, 200);

            prune(PRUNE_BEHIND_CAMERA);// | PRUNE_FARAWAY | PRUNE_HIGH_REPROJ_ERR, ODOMETER);

            reprojectionError(minError, maxError, avgError, featureCount, ODOMETER);

            if (mVerbose)
            {
                std::cout << "# INFO: Done." << std::endl;
                std::cout << "# INFO: Reprojection error after inter-map linking: avg = " << avgError
                          << " px | max = " << maxError << " px | count = " << featureCount << std::endl;
            }

            std::cout << "# INFO: Done." << std::endl;
        }

        visualize("opt2-BA-", ODOMETER);

        visualizeExtrinsics("opt2-extrinsics");

        if (saveWorkingData)
        {
            if (!findLoopClosures)
            {
                for (int i = 0; i < CAMERA_COUNT; ++i)
                {
                    std::ostringstream oss;
                    oss << "tmp_intrinsic_" << i << ".yaml";

                    boost::filesystem::path intrinsicPath(dataDir);
                    intrinsicPath /= oss.str();
                    mCameraParameters.at(i).write(intrinsicPath.string());
                }
            }

            boost::filesystem::path extrinsicPath(dataDir);
            extrinsicPath /= "tmp_extrinsic_2.txt";
            mExtrinsics.writeToFile(extrinsicPath.string());

            boost::filesystem::path graphPath(dataDir);
            graphPath /= "frames_2.sg";
            mGraph.writeToBinaryFile(graphPath.string());
        }
    }

    if (findLoopClosures && beginStage <= 3)
    {
        if (mVerbose)
        {
            std::cout << "# INFO: Building vocabulary tree... " << std::endl;
        }

        buildVocTree();

        if (mVerbose)
        {
            std::cout << "# INFO: Done." << std::endl;
        }

        if (mVerbose)
        {
            std::cout << "# INFO: Finding loop closures... " << std::endl;
        }

        std::vector<boost::tuple<int, int, FramePtr, FramePtr> > loopClosureFrameFrame;
        std::vector<Correspondence3D3D> loopClosure3D3D;
        findLoopClosure3D3D(loopClosureFrameFrame, loopClosure3D3D);

        for (size_t i = 0; i < loopClosure3D3D.size(); ++i)
        {
            Point3DFeaturePtr p1 = loopClosure3D3D.at(i).get<4>();
            Point3DFeaturePtr p2 = loopClosure3D3D.at(i).get<5>();

            p2->features2D().insert(p2->features2D().end(), p1->features2D().begin(), p1->features2D().end());
            std::sort(p2->features2D().begin(), p2->features2D().end());
            p2->features2D().erase(std::unique(p2->features2D().begin(), p2->features2D().end()), p2->features2D().end());

            std::vector<Point2DFeaturePtr> features2D = p2->features2D();
            for (size_t j = 0; j < features2D.size(); ++j)
            {
                features2D.at(j)->feature3D() = p2;
            }
        }

        visualizeFrameFrameCorrespondences("loop-p-p", loopClosureFrameFrame);

        if (mVerbose)
        {
            std::cout << "# INFO: Done." << std::endl;
            std::cout << "# INFO: Running BA on odometer data... " << std::endl;
        }

        // perform BA to optimize intrinsics, extrinsics and scene points
        optimize(CATA_ODOMETER, true, 200);

        prune(PRUNE_BEHIND_CAMERA);

        double minError, maxError, avgError;
        size_t featureCount;

        reprojectionError(minError, maxError, avgError, featureCount, ODOMETER);

        if (mVerbose)
        {
            std::cout << "# INFO: Done." << std::endl;
            std::cout << "# INFO: Reprojection error after loop closures: avg = " << avgError
                      << " px | max = " << maxError << " px | count = " << featureCount << std::endl;
        }

        visualize("opt3-BA-", ODOMETER);

        visualizeExtrinsics("opt3-extrinsics");

        if (saveWorkingData)
        {
            for (int i = 0; i < CAMERA_COUNT; ++i)
            {
                std::ostringstream oss;
                oss << "tmp_intrinsic_" << i << ".yaml";

                boost::filesystem::path intrinsicPath(dataDir);
                intrinsicPath /= oss.str();
                mCameraParameters.at(i).write(intrinsicPath.string());
            }

            boost::filesystem::path extrinsicPath(dataDir);
            extrinsicPath /= "tmp_extrinsic_3.txt";
            mExtrinsics.writeToFile(extrinsicPath.string());

            boost::filesystem::path graphPath(dataDir);
            graphPath /= "frames_3.sg";
            mGraph.writeToBinaryFile(graphPath.string());
        }
    }
}

void
CameraRigBA::setVerbose(bool verbose)
{
    mVerbose = verbose;
}

void
CameraRigBA::frameReprojectionError(const FramePtr& frame,
                                    const CataCameraParameters& cameraParameters,
                                    const Pose& T_cam_odo,
                                    double& minError, double& maxError, double& avgError,
                                    size_t& featureCount,
                                    int type) const
{
    minError = std::numeric_limits<double>::max();
    maxError = std::numeric_limits<double>::min();

    size_t count = 0;
    double totalError = 0.0;

    const std::vector<Point2DFeaturePtr>& features2D = frame->features2D();

    for (size_t i = 0; i < features2D.size(); ++i)
    {
        const Point2DFeatureConstPtr& feature2D = features2D.at(i);
        const Point3DFeatureConstPtr& feature3D = feature2D->feature3D();

        if (feature3D.get() == 0)
        {
            continue;
        }

        double error = 0.0;

        if (type == ODOMETER)
        {
            OdometerReprojectionError reprojErr(cameraParameters,
                                                feature2D->keypoint().pt.x, feature2D->keypoint().pt.y);

            double residuals[2];
            reprojErr(T_cam_odo.rotationData(),
                      T_cam_odo.translationData(),
                      frame->odometer()->positionData(),
                      frame->odometer()->yawData(),
                      feature3D->pointData(), residuals);

            error = hypot(residuals[0], residuals[1]);
        }
        else
        {
            CameraReprojectionError reprojErr(cameraParameters,
                                                feature2D->keypoint().pt.x, feature2D->keypoint().pt.y);

            double residuals[2];
            reprojErr(frame->camera()->rotationData(),
                      frame->camera()->translationData(),
                      feature3D->pointData(), residuals);

            error = hypot(residuals[0], residuals[1]);
        }

        if (minError > error)
        {
            minError = error;
        }
        if (maxError < error)
        {
            maxError = error;
        }
        totalError += error;
        ++count;
    }

    if (count == 0)
    {
        avgError = 0.0;
        minError = 0.0;
        maxError = 0.0;
        featureCount = count;

        return;
    }

    avgError = totalError / count;
    featureCount = count;
}

void
CameraRigBA::reprojectionError(double& minError, double& maxError,
                               double& avgError, size_t& featureCount,
                               int type) const
{
    minError = std::numeric_limits<double>::max();
    maxError = std::numeric_limits<double>::min();

    size_t count = 0;
    double totalError = 0.0;

    for (size_t i = 0; i < mCameras.size(); ++i)
    {
        Pose T_cam_odo(mExtrinsics.getGlobalCameraPose(i));

        for (size_t j = 0; j < mGraph.frameSegments(i).size(); ++j)
        {
            const FrameSegment& segment = mGraph.frameSegments(i).at(j);

            for (size_t k = 0; k < segment.size(); ++k)
            {
                double frameMinError;
                double frameMaxError;
                double frameAvgError;
                size_t frameFeatureCount;

                frameReprojectionError(segment.at(k),
                                       mCameraParameters.at(i),
                                       T_cam_odo,
                                       frameMinError, frameMaxError, frameAvgError, frameFeatureCount,
                                       type);

                if (minError > frameMinError)
                {
                    minError = frameMinError;
                }
                if (maxError < frameMaxError)
                {
                    maxError = frameMaxError;
                }
                totalError += frameAvgError * frameFeatureCount;
                count += frameFeatureCount;
            }
        }
    }

    if (count == 0)
    {
        avgError = 0.0;
        minError = 0.0;
        maxError = 0.0;
        featureCount = 0;

        return;
    }

    avgError = totalError / count;
    featureCount = count;
}

void
CameraRigBA::triangulateFeatures(FramePtr& frame1, FramePtr& frame2, FramePtr& frame3,
                                 const CataCamera& camera,
                                 const CataCameraParameters& cameraParameters,
                                 const Pose& T_cam_odo)
{
    // triangulate new feature correspondences seen in last 3 frames
    std::vector<std::vector<Point2DFeaturePtr> > featureCorrespondences;

    // use features that are seen in frames 0, 1, and 2
    find2D2DCorrespondences(frame3->features2D(), 3, featureCorrespondences);

//    if (mVerbose)
//    {
//        std::cout << "# INFO: Found " << featureCorrespondences.size() << " feature correspondences in last 3 frames." << std::endl;
//    }

    std::vector<cv::Point2f> ipoints[3];

    std::vector<std::vector<Point2DFeaturePtr> > untriFeatureCorrespondences;
    for (size_t i = 0; i < featureCorrespondences.size(); ++i)
    {
        std::vector<Point2DFeaturePtr>& fc = featureCorrespondences.at(i);

        Point2DFeaturePtr& f0 = fc.at(0);
        Point2DFeaturePtr& f1 = fc.at(1);
        Point2DFeaturePtr& f2 = fc.at(2);

        if (f0->feature3D().get() == 0 && f1->feature3D().get() == 0)
        {
            ipoints[0].push_back(f0->keypoint().pt);
            ipoints[1].push_back(f1->keypoint().pt);
            ipoints[2].push_back(f2->keypoint().pt);

            untriFeatureCorrespondences.push_back(fc);
        }

        if (f0->feature3D().get() != 0 && f1->feature3D().get() != 0)
        {
            f2->feature3D() = f1->feature3D();
            f2->feature3D()->features2D().push_back(f2);
            frame3->features3D().push_back(f2->feature3D());
        }
    }

//    if (mVerbose)
//    {
//        std::cout << "# INFO: Found " << untriFeatureCorrespondences.size() << " untriangulated feature correspondences." << std::endl;
//    }

    if (!untriFeatureCorrespondences.empty())
    {
        std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d> > points3D;
        std::vector<size_t> indices;

        Eigen::Matrix4d H_odo_cam = T_cam_odo.pose().inverse();

        Eigen::Matrix4d H1 = H_odo_cam * frame1->odometer()->pose().inverse();
        Eigen::Matrix4d H2 = H_odo_cam * frame2->odometer()->pose().inverse();
        Eigen::Matrix4d H3 = H_odo_cam * frame3->odometer()->pose().inverse();

        tvt(camera, cameraParameters,
            H1, ipoints[0],
            H2, ipoints[1],
            H3, ipoints[2],
            points3D, indices);

//        if (mVerbose)
//        {
//            std::cout << "# INFO: Triangulated " << points3D.size() << " new points." << std::endl;
//
//            if (!points3D.empty())
//            {
//                size_t count = 0;
//                double errorTotal = 0.0;
//                double errorMax = std::numeric_limits<double>::min();
//
//                for (size_t i = 0; i < points3D.size(); ++i)
//                {
//                    const cv::Point2f& feature2D = ipoints[0].at(indices.at(i));
//
//                    const Eigen::Vector3d& feature3D = points3D.at(i);
//
//                    OdometerReprojectionError reprojErr(cameraParameters,
//                                                        feature2D.x, feature2D.y);
//
//                    double residuals[2];
//                    reprojErr(T_cam_odo.rotationData(),
//                              T_cam_odo.translationData(),
//                              frame1->odometer()->positionData(),
//                              frame1->odometer()->yawData(),
//                              feature3D.data(), residuals);
//
//                    double error = hypot(residuals[0], residuals[1]);
//                    errorTotal += error;
//
//                    if (error > errorMax)
//                    {
//                        errorMax = error;
//                    }
//
//                    ++count;
//                }
//
//                double errorAvg = errorTotal / count;
//
//                std::cout << "# INFO: Reprojection error in frame n-2: avg = " << errorAvg
//                          << " px | max = " << errorMax << " px." << std::endl;
//
//                count = 0;
//                errorTotal = 0.0;
//                errorMax = std::numeric_limits<double>::min();
//
//                for (size_t i = 0; i < points3D.size(); ++i)
//                {
//                    const cv::Point2f& feature2D = ipoints[1].at(indices.at(i));
//
//                    const Eigen::Vector3d& feature3D = points3D.at(i);
//
//                    OdometerReprojectionError reprojErr(cameraParameters,
//                                                        feature2D.x, feature2D.y);
//
//                    double residuals[2];
//                    reprojErr(T_cam_odo.rotationData(),
//                              T_cam_odo.translationData(),
//                              frame2->odometer()->positionData(),
//                              frame2->odometer()->yawData(),
//                              feature3D.data(), residuals);
//
//                    double error = hypot(residuals[0], residuals[1]);
//                    errorTotal += error;
//
//                    if (error > errorMax)
//                    {
//                        errorMax = error;
//                    }
//
//                    ++count;
//                }
//
//                errorAvg = errorTotal / count;
//
//                std::cout << "# INFO: Reprojection error in frame n-1: avg = " << errorAvg
//                          << " px | max = " << errorMax << " px." << std::endl;
//
//                count = 0;
//                errorTotal = 0.0;
//                errorMax = std::numeric_limits<double>::min();
//
//                for (size_t i = 0; i < points3D.size(); ++i)
//                {
//                    const cv::Point2f& feature2D = ipoints[2].at(indices.at(i));
//
//                    const Eigen::Vector3d& feature3D = points3D.at(i);
//
//                    OdometerReprojectionError reprojErr(cameraParameters,
//                                                        feature2D.x, feature2D.y);
//
//                    double residuals[2];
//                    reprojErr(T_cam_odo.rotationData(),
//                              T_cam_odo.translationData(),
//                              frame3->odometer()->positionData(),
//                              frame3->odometer()->yawData(),
//                              feature3D.data(), residuals);
//
//                    double error = hypot(residuals[0], residuals[1]);
//                    errorTotal += error;
//
//                    if (error > errorMax)
//                    {
//                        errorMax = error;
//                    }
//
//                    ++count;
//                }
//
//                errorAvg = errorTotal / count;
//
//                std::cout << "# INFO: Reprojection error in frame n: avg = " << errorAvg
//                          << " px | max = " << errorMax << " px." << std::endl;
//            }
//        }

        for (size_t i = 0; i < points3D.size(); ++i)
        {
            Point3DFeaturePtr point3D(new Point3DFeature);

            point3D->point() = points3D.at(i);

            std::vector<Point2DFeaturePtr>& fc = untriFeatureCorrespondences.at(indices.at(i));

            for (int j = 0; j < 3; ++j)
            {
                Point2DFeaturePtr& pt = fc.at(j);

                point3D->features2D().push_back(pt);
                pt->feature3D() = point3D;
            }

            frame3->features3D().push_back(point3D);
        }
    }

//    if (mVerbose)
//    {
//        double minError, maxError, avgError;
//        size_t featureCount;
//
//        frameReprojectionError(frame3, cameraParameters, T_cam_odo, minError, maxError, avgError, featureCount);
//
//        std::cout << "# INFO: Frame reprojection error: min = " << minError << " | max = " << maxError << " | avg = " << avgError << std::endl;
//    }
}

void
CameraRigBA::find2D2DCorrespondences(const std::vector<Point2DFeaturePtr>& features,
                                     int nViews,
                                     std::vector<std::vector<Point2DFeaturePtr> >& correspondences) const
{
    // find feature correspondences across n views starting backward from
    // specified feature set in nth view
    if (nViews < 2)
    {
        return;
    }

    correspondences.reserve(features.size());

    for (size_t i = 0; i < features.size(); ++i)
    {
        Point2DFeaturePtr pt[nViews];

        pt[nViews - 1] = features.at(i);
        bool foundCorrespondences = true;

        for (int j = nViews - 1; j > 0; --j)
        {
            if (pt[j]->prevMatches().empty() || pt[j]->bestPrevMatchIdx() == -1)
            {
                foundCorrespondences = false;
                break;
            }

            pt[j - 1] = pt[j]->prevMatch();
        }

        if (!foundCorrespondences)
        {
            continue;
        }

        std::vector<Point2DFeaturePtr> correspondence(nViews);
        for (int j = 0; j < nViews; ++j)
        {
            correspondence.at(j) = pt[j];
        }

        correspondences.push_back(correspondence);
    }
}

void
CameraRigBA::buildVocTree(void)
{
    mVid2FidLUT.clear();

    // build vocabulary tree
    std::vector<std::vector<std::vector<float> > > features;

    for (size_t cameraIdx = 0; cameraIdx < CAMERA_COUNT; ++cameraIdx)
    {
        std::vector<FrameSegment>& segments = mGraph.frameSegments(cameraIdx);

        for (size_t segmentIdx = 0; segmentIdx < segments.size(); ++segmentIdx)
        {
            FrameSegment& segment = segments.at(segmentIdx);

            for (size_t frameIdx = 0; frameIdx < segment.size(); ++frameIdx)
            {
                FramePtr& frame = segment.at(frameIdx);

                FrameID fid;
                fid.cameraIdx = cameraIdx;
                fid.segmentIdx = segmentIdx;
                fid.frameIdx = frameIdx;
                mVid2FidLUT.push_back(fid);

                features.push_back(frameToBOW(frame));
            }
        }
    }

    // branching factor and depth levels
    const int k = 9;
    const int L = 3;
    const DBoW2::WeightingType weight = DBoW2::TF_IDF;
    const DBoW2::ScoringType score = DBoW2::L1_NORM;

    Surf64Vocabulary voc(k, L, weight, score);
    voc.create(features);

    mDb.setVocabulary(voc);
    for (size_t i = 0; i < features.size(); ++i)
    {
        mDb.add(features.at(i));
    }
}

std::vector<std::vector<float> >
CameraRigBA::frameToBOW(const FrameConstPtr& frame) const
{
    std::vector<std::vector<float> > bow;

    const std::vector<Point2DFeaturePtr>& features2D = frame->features2D();
    for (size_t i = 0; i < features2D.size(); ++i)
    {
        const Point2DFeatureConstPtr& feature2D = features2D.at(i);

        if (feature2D->feature3D().get() == 0)
        {
            continue;
        }

        const cv::Mat& dtor = feature2D->descriptor();

        std::vector<float> w(dtor.cols);
        for (int j = 0; j < dtor.cols; ++j)
        {
            w.at(j) = dtor.at<float>(0,j);
        }

        bow.push_back(w);
    }

    return bow;
}

void
CameraRigBA::findLoopClosure3D3D(std::vector<boost::tuple<int, int, FramePtr, FramePtr> >& correspondencesFrameFrame,
                                 std::vector<Correspondence3D3D>& correspondences3D3D,
                                 double reprojErrorThresh)
{
    std::vector<Correspondence3D3D> corr3D3D[CAMERA_COUNT];
    std::vector<boost::tuple<int, int, FramePtr, FramePtr> > corrFF[CAMERA_COUNT];

    Glib::Thread* threads[CAMERA_COUNT];
    for (int i = 0; i < CAMERA_COUNT; ++i)
    {
        threads[i] = Glib::Thread::create(sigc::bind(sigc::mem_fun(*this, &CameraRigBA::findLoopClosure3D3DHelper),
                                                     i, &corrFF[i], &corr3D3D[i], reprojErrorThresh));
    }

    for (int i = 0; i < CAMERA_COUNT; ++i)
    {
        threads[i]->join();

        correspondencesFrameFrame.insert(correspondencesFrameFrame.end(), corrFF[i].begin(), corrFF[i].end());
        correspondences3D3D.insert(correspondences3D3D.end(), corr3D3D[i].begin(), corr3D3D[i].end());
    }
}

void
CameraRigBA::findLoopClosure3D3DHelper(int cameraIdx,
                                       std::vector<boost::tuple<int, int, FramePtr, FramePtr> >* corrFF,
                                       std::vector<Correspondence3D3D>* corr3D3D,
                                       double reprojErrorThresh)
{
    std::vector<Pose, Eigen::aligned_allocator<Pose> > T_cam_odo(mCameras.size());
    for (size_t i = 0; i < mCameras.size(); ++i)
    {
        T_cam_odo.at(i) = Pose(mExtrinsics.getGlobalCameraPose(i));
    }

    // find closest matching images
    std::vector<FrameSegment>& segments = mGraph.frameSegments(cameraIdx);

    for (int segmentIdx = 0; segmentIdx < segments.size(); ++segmentIdx)
    {
        FrameSegment& segment = segments.at(segmentIdx);

        for (int frameIdx = 0; frameIdx < segment.size(); ++frameIdx)
        {
            FramePtr& frame1 = segment.at(frameIdx);

            DBoW2::QueryResults ret;
            mDb.query(frameToBOW(frame1), ret, kNearestImageMatches);

            std::vector<Correspondence3D3D> corr3D3DBest;
            FramePtr frame2Best;
            FrameID fidBest;
            int nInliersBest;
            for (size_t i = 0; i < ret.size(); ++i)
            {
                FrameID fid = mVid2FidLUT.at(ret.at(i).Id);

                if (fid.cameraIdx == cameraIdx &&
                    fid.segmentIdx == segmentIdx &&
                    abs(fid.frameIdx - frameIdx) < 20)
                {
                    continue;
                }

                FramePtr& frame2 = mGraph.frameSegments(fid.cameraIdx).at(fid.segmentIdx).at(fid.frameIdx);

                // mark 3D-3D correspondences between maps
                std::vector<cv::DMatch> matches = matchFeatures(frame1->features2D(), frame2->features2D());

                std::vector<std::pair<Point2DFeaturePtr, Point2DFeaturePtr> > corr2D2D;
                for (size_t j = 0; j < matches.size(); ++j)
                {
                    cv::DMatch& match = matches.at(j);

                    corr2D2D.push_back(std::make_pair(frame1->features2D().at(match.queryIdx),
                                                      frame2->features2D().at(match.trainIdx)));
                }

                if (corr2D2D.size() < kMinLoopCorrespondences2D2D)
                {
                    continue;
                }

                std::vector<cv::Point2f> points1, points2;
                points1.reserve(corr2D2D.size());
                points2.reserve(corr2D2D.size());

                for (size_t j = 0; j < corr2D2D.size(); ++j)
                {
                    Point2DFeaturePtr& pf1 = corr2D2D.at(j).first;
                    Point2DFeaturePtr& pf2 = corr2D2D.at(j).second;

                    cv::Point2f rectPt1, rectPt2;
                    rectifyImagePoint(*(mCameras.at(cameraIdx)), mCameraParameters.at(cameraIdx), pf1->keypoint().pt, rectPt1, kNominalFocalLength);
                    rectifyImagePoint(*(mCameras.at(fid.cameraIdx)), mCameraParameters.at(fid.cameraIdx), pf2->keypoint().pt, rectPt2, kNominalFocalLength);

                    points1.push_back(rectPt1);
                    points2.push_back(rectPt2);
                }

                cv::Point2f pp(mCameraParameters.at(0).imageWidth() / 2.0f, mCameraParameters.at(0).imageHeight() / 2.0f);

                cv::Mat E, inlierMat;
                E = findEssentialMat(points1, points2, kNominalFocalLength, pp, CV_FM_RANSAC, 0.99, reprojErrorThresh, 1000, inlierMat);

                if (cv::countNonZero(inlierMat) < kMinLoopCorrespondences2D2D)
                {
                    continue;
                }

                std::vector<Correspondence3D3D> corr3D3D;
                for (int j = 0; j < corr2D2D.size(); ++j)
                {
                    if (inlierMat.at<unsigned char>(0,j))
                    {
                        Point3DFeaturePtr& p1 = corr2D2D.at(j).first->feature3D();
                        Point3DFeaturePtr& p2 = corr2D2D.at(j).second->feature3D();

//                        Eigen::Vector3d p_cam1 = (frame1->odometer()->pose() * T_cam_odo.at(cameraIdx).pose()).block<3,1>(0,3);
//                        Eigen::Vector3d p_cam2 = (frame2->odometer()->pose() * T_cam_odo.at(fid.cameraIdx).pose()).block<3,1>(0,3);
//
//                        Eigen::Vector3d dp_cam = p_cam2 - p_cam1;
//                        Eigen::Vector3d dp = p2->point() - p1->point();
//
//                        double theta = acos(dp.normalized().dot(dp_cam.normalized()));
//                        if (fabs(theta) > kRelativeAngleThresh3D3D)
//                        {
//                            continue;
//                        }
//
//                        double relativeDistance = (p1->point() - p2->point()).norm() / (p_cam1 - p_cam2).norm();
//
//                        if (relativeDistance > kRelativeDistanceThresh3D3D)
//                        {
//                            continue;
//                        }

                        corr3D3D.push_back(boost::make_tuple(cameraIdx, fid.cameraIdx,
                                                             frame1, frame2,
                                                             p1, p2));
                    }
                }

                if (corr3D3D.size() > corr3D3DBest.size())
                {
                    corr3D3DBest = corr3D3D;
                    frame2Best = frame2;
                    fidBest = fid;
                    nInliersBest = cv::countNonZero(inlierMat);
                }
            }

            if (!corr3D3DBest.empty())
            {
                corrFF->push_back(boost::make_tuple(cameraIdx, cameraIdx, frame1, frame2Best));

                if (mVerbose)
                {
                    std::cout << "# INFO: Image match: " << cameraIdx << "," << segmentIdx << "," << frameIdx << " -> "
                              << fidBest.cameraIdx << "," << fidBest.segmentIdx << "," << fidBest.frameIdx << " with "
                              << nInliersBest << " 2D-2D correspondences and "
                              << corr3D3DBest.size() << " 3D-3D correspondences." << std::endl;
                }

                corr3D3D->insert(corr3D3D->end(), corr3D3DBest.begin(), corr3D3DBest.end());

                visualize3D3DCorrespondences("loop-3d-3d", corr3D3DBest);
            }
        }
    }

    if (mVerbose)
    {
        std::cout << "# INFO: # loop 3D-3D correspondences for camera "
                  << cameraIdx << ": " << corr3D3D->size() << std::endl;
    }
}

std::vector<cv::DMatch>
CameraRigBA::matchFeatures(const std::vector<Point2DFeaturePtr>& features1,
                           const std::vector<Point2DFeaturePtr>& features2) const
{
    cv::BFMatcher descriptorMatcher(cv::NORM_L2, false);

    std::vector<size_t> indices1, indices2;
    cv::Mat dtor1 = buildDescriptorMat(features1, indices1);
    cv::Mat dtor2 = buildDescriptorMat(features2, indices2);

    std::vector<std::vector<cv::DMatch> > candidateFwdMatches;
    descriptorMatcher.knnMatch(dtor1, dtor2, candidateFwdMatches, 2);

    std::vector<std::vector<cv::DMatch> > candidateRevMatches;
    descriptorMatcher.knnMatch(dtor2, dtor1, candidateRevMatches, 2);

    std::vector<std::vector<cv::DMatch> > fwdMatches(candidateFwdMatches.size());
    for (size_t i = 0; i < candidateFwdMatches.size(); ++i)
    {
        std::vector<cv::DMatch>& match = candidateFwdMatches.at(i);

        if (match.size() < 2)
        {
            continue;
        }

        float distanceRatio = match.at(0).distance / match.at(1).distance;

        if (distanceRatio < kMaxDistanceRatio)
        {
            fwdMatches.at(i).push_back(match.at(0));
        }
    }

    std::vector<std::vector<cv::DMatch> > revMatches(candidateRevMatches.size());
    for (size_t i = 0; i < candidateRevMatches.size(); ++i)
    {
        std::vector<cv::DMatch>& match = candidateRevMatches.at(i);

        if (match.size() < 2)
        {
            continue;
        }

        float distanceRatio = match.at(0).distance / match.at(1).distance;

        if (distanceRatio < kMaxDistanceRatio)
        {
            revMatches.at(i).push_back(match.at(0));
        }
    }

    // cross-check
    std::vector<cv::DMatch> matches;
    for (size_t i = 0; i < fwdMatches.size(); ++i)
    {
        if (fwdMatches.at(i).empty())
        {
            continue;
        }

        cv::DMatch& fwdMatch = fwdMatches.at(i).at(0);

        if (revMatches.at(fwdMatch.trainIdx).empty())
        {
            continue;
        }

        cv::DMatch& revMatch = revMatches.at(fwdMatch.trainIdx).at(0);

        if (fwdMatch.queryIdx == revMatch.trainIdx &&
            fwdMatch.trainIdx == revMatch.queryIdx)
        {
            cv::DMatch match;
            match.queryIdx = indices1.at(fwdMatch.queryIdx);
            match.trainIdx = indices2.at(revMatch.queryIdx);

            matches.push_back(match);
        }
    }

    return matches;
}

void
CameraRigBA::findLocalInterMap2D2DCorrespondences(std::vector<Correspondence2D2D>& correspondences2D2D,
                                                  double reprojErrorThresh)
{
    std::map<uint64_t, std::vector<FramePtr> > pathMap;

    for (int cameraIdx = 0; cameraIdx < CAMERA_COUNT; ++cameraIdx)
    {
        std::vector<FrameSegment>& segments = mGraph.frameSegments(cameraIdx);

        for (size_t segmentIdx = 0; segmentIdx < segments.size(); ++segmentIdx)
        {
            FrameSegment& segment = segments.at(segmentIdx);

            for (size_t frameIdx = 0; frameIdx < segment.size(); ++frameIdx)
            {
                FramePtr& frame = segment.at(frameIdx);

                std::vector<FramePtr>& frames = pathMap[frame->odometer()->timeStamp()];

                if (frames.empty())
                {
                    frames.resize(CAMERA_COUNT);
                }

                frames.at(cameraIdx) = frame;
            }
        }
    }

    std::list<FramePtr> windows[CAMERA_COUNT];
    int pathNodeIdx = -1;
    for (std::map<uint64_t, std::vector<FramePtr> >::iterator it = pathMap.begin();
            it != pathMap.end(); ++it)
    {
        ++pathNodeIdx;

//        if (pathNodeIdx > 60)
//        {
//            return;
//        }

        std::vector<FramePtr>& frames = it->second;

        std::vector<FramePtr> localFrameMaps[CAMERA_COUNT];
        for (int cameraIdx = 0; cameraIdx < CAMERA_COUNT; ++cameraIdx)
        {
            std::list<FramePtr>& window = windows[cameraIdx];

            if (frames.at(cameraIdx).get() != 0)
            {
                windows[cameraIdx].push_front(frames.at(cameraIdx));
            }

            std::list<FramePtr>::iterator itWindow = windows[cameraIdx].begin();
            bool init = false;
            Eigen::Vector2d lastOdoPos;

            double dist = 0.0;
            while (itWindow != windows[cameraIdx].end() && dist < kLocalMapWindowDistance)
            {
                if (!init)
                {
                    lastOdoPos = (*itWindow)->odometer()->position();

                    init = true;

                    ++itWindow;

                    continue;
                }

                dist += ((*itWindow)->odometer()->position() - lastOdoPos).norm();

                lastOdoPos = (*itWindow)->odometer()->position();

                if (dist < kLocalMapWindowDistance)
                {
                    ++itWindow;
                }
            }

            if (itWindow != windows[cameraIdx].end())
            {
                windows[cameraIdx].erase(itWindow, windows[cameraIdx].end());
            }
        }

        if (mVerbose)
        {
            std::cout << "# INFO: Entering path node " << pathNodeIdx
                      << "/" << pathMap.size() - 1 << " [ ";

            for (int i = 0; i < CAMERA_COUNT; ++i)
            {
                std::cout << windows[i].size() << " ";
            }
            std::cout << "]" << std::endl;
        }

        // project each map into other cameras
        for (int cameraIdx1 = 0; cameraIdx1 < CAMERA_COUNT; ++cameraIdx1)
        {
            FramePtr& frame1 = frames.at(cameraIdx1);

            if (frame1.get() == 0)
            {
                continue;
            }

            if (frame1->features2D().empty())
            {
                continue;
            }

            Glib::Thread* threads[CAMERA_COUNT];
            std::vector<Correspondence2D2D> subCorr2D2D[CAMERA_COUNT];
            for (int cameraIdx2 = 0; cameraIdx2 < CAMERA_COUNT; ++cameraIdx2)
            {
                if (cameraIdx1 == cameraIdx2)
                {
                    continue;
                }

                std::vector<FramePtr> window;
                window.insert(window.end(), windows[cameraIdx2].begin(), windows[cameraIdx2].end());

                threads[cameraIdx2] = Glib::Thread::create(sigc::bind(sigc::mem_fun(*this, &CameraRigBA::matchFrameToWindow),
                                                                      cameraIdx1, cameraIdx2, frame1, window,
                                                                      &subCorr2D2D[cameraIdx2],
                                                                      reprojErrorThresh));
            }

            for (int cameraIdx2 = 0; cameraIdx2 < CAMERA_COUNT; ++cameraIdx2)
            {
                if (cameraIdx1 == cameraIdx2)
                {
                    continue;
                }

                threads[cameraIdx2]->join();

                correspondences2D2D.insert(correspondences2D2D.end(), subCorr2D2D[cameraIdx2].begin(), subCorr2D2D[cameraIdx2].end());
            }
        }
    }
}

void
CameraRigBA::matchFrameToWindow(int cameraIdx1, int cameraIdx2,
                                FramePtr& frame1,
                                std::vector<FramePtr>& window,
                                std::vector<Correspondence2D2D>* correspondences2D2D,
                                double reprojErrorThresh)
{
    if (window.empty())
    {
        return;
    }

    if (frame1->image().empty())
    {
        return;
    }

    Glib::Thread* threads[window.size()];
    std::vector<std::pair<Point2DFeaturePtr, Point2DFeaturePtr> > corr2D2D[window.size()];

    int windowIdx = -1;
    for (std::vector<FramePtr>::iterator itFrame2 = window.begin(); itFrame2 != window.end(); ++itFrame2)
    {
        ++windowIdx;
        FramePtr& frame2 = *itFrame2;

        threads[windowIdx] = Glib::Thread::create(sigc::bind(sigc::mem_fun(*this, &CameraRigBA::matchFrameToFrame),
                                                             cameraIdx1, cameraIdx2, frame1, frame2,
                                                             &corr2D2D[windowIdx],
                                                             reprojErrorThresh));
    }

    int windowIdxBest = -1;
    std::vector<std::pair<Point2DFeaturePtr, Point2DFeaturePtr> > corr2D2DBest;

    for (windowIdx = 0; windowIdx < window.size(); ++windowIdx)
    {
        threads[windowIdx]->join();

        if (corr2D2D[windowIdx].size() > corr2D2DBest.size())
        {
            windowIdxBest = windowIdx;
            corr2D2DBest = corr2D2D[windowIdx];
        }

//        if (mVerbose && !corr3D3D[windowIdx].empty())
//        {
//            std::cout << "# INFO:   cam " << cameraIdx1 << " - cam " << cameraIdx2
//                      << ": window " << windowIdx
//                      << " | " << corr2D2D[windowIdx].size() << " 2D-2D"
//                      << " | " << corr3D3D[windowIdx].size() << " 3D-3D" << std::endl;
//        }
    }

    if (!corr2D2DBest.empty())
    {
        FramePtr& frame2 = window.at(windowIdxBest);

        correspondences2D2D->insert(correspondences2D2D->end(), corr2D2DBest.begin(), corr2D2DBest.end());

        if (mVerbose)
        {
            std::cout << "# INFO: Best: cam " << cameraIdx1 << " - cam " << cameraIdx2
                      << ": window " << windowIdxBest
                      << " | " << corr2D2DBest.size() << " 2D-2D" << std::endl;

        }

        visualize3D3DCorrespondences("local-inter-3d-3d", corr2D2DBest);
    }
}

void
CameraRigBA::matchFrameToFrame(int cameraIdx1, int cameraIdx2,
                               FramePtr& frame1, FramePtr& frame2,
                               std::vector<Correspondence2D2D>* corr2D2D,
                               double reprojErrorThresh)
{
    std::vector<size_t> inliers2D2D;

    if (frame2.get() == 0)
    {
        return;
    }

    if (frame2->features2D().empty())
    {
        return;
    }

    if (frame2->image().empty())
    {
        return;
    }

    Pose T_cam_odo1(mExtrinsics.getGlobalCameraPose(cameraIdx1));
    Pose T_cam_odo2(mExtrinsics.getGlobalCameraPose(cameraIdx2));
    Pose T_odo_cam1(mExtrinsics.getGlobalCameraPose(cameraIdx1).inverse());
    Pose T_odo_cam2(mExtrinsics.getGlobalCameraPose(cameraIdx2).inverse());

    Eigen::Matrix4d H_cam1 = T_odo_cam1.pose() * frame1->odometer()->pose().inverse();
    Eigen::Matrix4d H_cam2 = T_odo_cam2.pose() * frame2->odometer()->pose().inverse();

    // compute average rotation between camera pair
    Eigen::JacobiSVD<Eigen::Matrix3d> svd(H_cam1.block<3,3>(0,0) +
                                          H_cam2.block<3,3>(0,0),
                                          Eigen::ComputeFullU | Eigen::ComputeFullV);

    Eigen::Matrix3d avgR = svd.matrixU() * svd.matrixV().transpose();

    Eigen::Matrix3d R1 = avgR * H_cam1.block<3,3>(0,0).transpose();
    Eigen::Matrix3d R2 = avgR * H_cam2.block<3,3>(0,0).transpose();

    cv::Mat R1_cv, R2_cv;
    cv::eigen2cv(R1, R1_cv);
    cv::eigen2cv(R2, R2_cv);

    cv::Mat mapX1, mapY1, mapX2, mapY2;
    mCameraCalibs.at(cameraIdx1)->initUndistortRectifyMap(mapX1, mapY1,
                                                          kNominalFocalLength, kNominalFocalLength,
                                                          cv::Size(0, 0),
                                                          -1.0f, -1.0f, R1_cv);
    mCameraCalibs.at(cameraIdx2)->initUndistortRectifyMap(mapX2, mapY2,
                                                          kNominalFocalLength, kNominalFocalLength,
                                                          cv::Size(0, 0),
                                                          -1.0f, -1.0f, R2_cv);

    cv::Mat rimg1, rimg2;
    cv::remap(frame1->image(), rimg1, mapX1, mapY1, cv::INTER_LINEAR);
    cv::remap(frame2->image(), rimg2, mapX2, mapY2, cv::INTER_LINEAR);

    cv::Ptr<SurfGPU> surf = SurfGPU::instance(500.0);

    std::vector<cv::KeyPoint> rkeypoints1, rkeypoints2;
    std::vector<cv::DMatch> rmatches;

    surf->match(rimg1, rkeypoints1, rimg2, rkeypoints2, rmatches);

    if (rmatches.size() < kMinInterCorrespondences2D2D)
    {
        return;
    }

    std::vector<cv::Point2f> rpoints1, rpoints2;
    for (size_t i = 0; i < rmatches.size(); ++i)
    {
        cv::DMatch& match = rmatches.at(i);

        rpoints1.push_back(rkeypoints1.at(match.queryIdx).pt);
        rpoints2.push_back(rkeypoints2.at(match.trainIdx).pt);
    }

    cv::Point2f pp(mCameraParameters.at(0).imageWidth() / 2.0f, mCameraParameters.at(0).imageHeight() / 2.0f);

    cv::Mat E, inlierMat;
    E = findEssentialMat(rpoints1, rpoints2, kNominalFocalLength, pp, CV_FM_RANSAC, 0.99, reprojErrorThresh, 1000, inlierMat);

    if (cv::countNonZero(inlierMat) < kMinInterCorrespondences2D2D)
    {
        return;
    }

    if (0)
    {
        static boost::mutex rmutex;
        rmutex.lock();

        static int rcount = 0;
        std::ostringstream oss;
        oss << "r-inter-map-matches-" << cameraIdx1 << "-" << cameraIdx2 << "-" << rcount << ".png";

        std::vector<cv::DMatch> inlierRMatches;
        for (size_t i = 0; i < rmatches.size(); ++i)
        {
            if (inlierMat.at<unsigned char>(0, i) != 0)
            {
                inlierRMatches.push_back(rmatches.at(i));
            }
        }

        cv::Mat sketch;
        cv::drawMatches(rimg1, rkeypoints1, rimg2, rkeypoints2, inlierRMatches, sketch);

        cv::imwrite(oss.str(), sketch);

        oss.str(""); oss.clear();
        oss << "r" << cameraIdx1 << "img" << rcount << ".png";
        cv::imwrite(oss.str(), frame1->image());

        oss.str(""); oss.clear();
        oss << "r" << cameraIdx2 << "img" << rcount << ".png";
        cv::imwrite(oss.str(), frame2->image());

        ++rcount;

        rmutex.unlock();
    }

//    cv::Mat R_cv, t_cv;
//    recoverPose(E, rpoints1, rpoints2, R_cv, t_cv, kNominalFocalLength, pp, inlierMat);
//
//    Eigen::Matrix3d R;
//    cv::cv2eigen(R_cv, R);
//
//    // error quaternion
//    Eigen::Quaterniond q(R);
//    double theta = (Eigen::Vector3d(q.x(), q.y(), q.z()) * 2.0).norm();
//
//    if (fabs(theta) > kRelativeAngleThresh3D3D)
//    {
//        return;
//    }

    Eigen::Matrix4d H1 = Eigen::Matrix4d::Identity();
    H1.block<3,3>(0,0) = R1;
    Eigen::Matrix4d H_rcam1 = H1 * H_cam1;

    Eigen::Matrix4d H2 = Eigen::Matrix4d::Identity();
    H2.block<3,3>(0,0) = R2;
    Eigen::Matrix4d H_rcam2 = H2 * H_cam2;

    std::vector<std::pair<Point2DFeaturePtr, Point2DFeaturePtr> > candidateCorr2D2D(rmatches.size());
    for (size_t i = 0; i < rmatches.size(); ++i)
    {
        if (inlierMat.at<unsigned char>(0, i) == 0)
        {
            continue;
        }

        cv::Point2f& rp = rpoints1.at(i);

        float kpDistMin = std::numeric_limits<float>::max();
        Point2DFeaturePtr p2DBest;
        for (size_t j = 0; j < frame1->features2D().size(); ++j)
        {
            Point2DFeaturePtr& p2D = frame1->features2D().at(j);
            Point3DFeaturePtr& p3D = p2D->feature3D();

            if (p3D.get() == 0)
            {
                continue;
            }

            Eigen::Vector3d P_rcam = transformPoint(H_rcam1, p3D->point());

            Eigen::Vector2d p_rcam = (kNominalFocalLength / P_rcam(2)) * P_rcam.block<2,1>(0,0);
            p_rcam += Eigen::Vector2d(mCameraParameters.at(cameraIdx1).imageWidth() / 2.0,
                                      mCameraParameters.at(cameraIdx1).imageHeight() / 2.0);

            if (p_rcam(0) < 0.0 || p_rcam(0) > mCameraParameters.at(cameraIdx1).imageWidth() - 1 ||
                p_rcam(1) < 0.0 || p_rcam(1) > mCameraParameters.at(cameraIdx1).imageHeight() - 1)
            {
                continue;
            }

            float kpDist = hypot(p_rcam(0) - rp.x, p_rcam(1) - rp.y);
            if (kpDist < kpDistMin)
            {
                kpDistMin = kpDist;
                p2DBest = p2D;
            }
        }

        if (kpDistMin < reprojErrorThresh)
        {
            candidateCorr2D2D.at(i).first = p2DBest;
        }

        rp = rpoints2.at(i);

        kpDistMin = std::numeric_limits<float>::max();
        for (size_t j = 0; j < frame2->features2D().size(); ++j)
        {
            Point2DFeaturePtr& p2D = frame2->features2D().at(j);
            Point3DFeaturePtr& p3D = p2D->feature3D();

            if (p3D.get() == 0)
            {
                continue;
            }

            Eigen::Vector3d P_rcam = transformPoint(H_rcam2, p3D->point());

            Eigen::Vector2d p_rcam = (kNominalFocalLength / P_rcam(2)) * P_rcam.block<2,1>(0,0);
            p_rcam += Eigen::Vector2d(mCameraParameters.at(cameraIdx2).imageWidth() / 2.0,
                                      mCameraParameters.at(cameraIdx2).imageHeight() / 2.0);

            if (p_rcam(0) < 0.0 || p_rcam(0) > mCameraParameters.at(cameraIdx2).imageWidth() - 1 ||
                p_rcam(1) < 0.0 || p_rcam(1) > mCameraParameters.at(cameraIdx2).imageHeight() - 1)
            {
                continue;
            }

            float kpDist = hypot(p_rcam(0) - rp.x, p_rcam(1) - rp.y);
            if (kpDist < kpDistMin)
            {
                kpDistMin = kpDist;
                p2DBest = p2D;
            }
        }

        if (kpDistMin < reprojErrorThresh)
        {
            candidateCorr2D2D.at(i).second = p2DBest;
        }
    }

    if (0)
    {
        std::vector<cv::KeyPoint> keypoints1, keypoints2;
        std::vector<cv::DMatch> matches;
        for (size_t i = 0; i < candidateCorr2D2D.size(); ++i)
        {
            Point2DFeaturePtr& p1 = candidateCorr2D2D.at(i).first;
            Point2DFeaturePtr& p2 = candidateCorr2D2D.at(i).second;

            if (p1.get() == 0 || p2.get() == 0)
            {
                continue;
            }

            keypoints1.push_back(p1->keypoint());
            keypoints2.push_back(p2->keypoint());

            cv::DMatch match;
            match.queryIdx = keypoints1.size() - 1;
            match.trainIdx = keypoints2.size() - 1;
            matches.push_back(match);
        }

        static boost::mutex mutex;
        mutex.lock();

        static int count = 0;
        std::ostringstream oss;
        oss << "ur-inter-map-matches-" << cameraIdx1 << "-" << cameraIdx2 << "-" << count << ".png";

        cv::Mat sketch;
        cv::drawMatches(frame1->image(), keypoints1, frame2->image(), keypoints2, matches, sketch);

        cv::imwrite(oss.str(), sketch);

        oss.str(""); oss.clear();
        oss << "ur" << cameraIdx1 << "img" << count << ".png";
        cv::imwrite(oss.str(), frame1->image());

        oss.str(""); oss.clear();
        oss << "ur" << cameraIdx2 << "img" << count << ".png";
        cv::imwrite(oss.str(), frame2->image());

        ++count;

        mutex.unlock();
    }

    Eigen::Matrix4d H_cam1_cam2 = H_cam2 * H_cam1.inverse();
    for (size_t i = 0; i < candidateCorr2D2D.size(); ++i)
    {
        Point2DFeaturePtr& p1 = candidateCorr2D2D.at(i).first;
        Point2DFeaturePtr& p2 = candidateCorr2D2D.at(i).second;

        if (p1.get() == 0 || p2.get() == 0)
        {
            continue;
        }

//        cv::Point2f rp1_cv;
//        rectifyImagePoint(*(mCameras.at(cameraIdx1)), mCameraParameters.at(cameraIdx1),
//                          p1->keypoint().pt, rp1_cv);
//        rp1_cv.x -= mCameraParameters.at(cameraIdx1).imageWidth() / 2.0f;
//        rp1_cv.y -= mCameraParameters.at(cameraIdx1).imageHeight() / 2.0f;
//
//        Eigen::Vector3d rp1;
//        rp1 << rp1_cv.x, rp1_cv.y, 1.0;
//
//        cv::Point2f rp2_cv;
//        rectifyImagePoint(*(mCameras.at(cameraIdx2)), mCameraParameters.at(cameraIdx2),
//                          p2->keypoint().pt, rp2_cv);
//        rp2_cv.x -= mCameraParameters.at(cameraIdx2).imageWidth() / 2.0f;
//        rp2_cv.y -= mCameraParameters.at(cameraIdx2).imageHeight() / 2.0f;
//
//        Eigen::Vector3d rp2;
//        rp2 << rp2_cv.x, rp2_cv.y, 1.0;
//
//        double reprojErr = sqrt(sampsonError(H_cam1_cam2, rp1, rp2)) * kNominalFocalLength;
//
//        if (reprojErr > kMaxReprojErr)
//        {
//            continue;
//        }

        corr2D2D->push_back(candidateCorr2D2D.at(i));
    }
}

void
CameraRigBA::visualizeFrameFrameCorrespondences(const std::string& overlayName,
                                                const std::vector<boost::tuple<int, int, FramePtr, FramePtr> >& correspondencesFrameFrame) const
{
    GLOverlayExtended overlay(overlayName, VCharge::COORDINATE_FRAME_GLOBAL);

    // visualize camera poses and 3D scene points
    overlay.clear();
    overlay.lineWidth(2.0f);

    for (size_t i = 0; i < correspondencesFrameFrame.size(); ++i)
    {
        int cameraIdx1 = correspondencesFrameFrame.at(i).get<0>();
        int cameraIdx2 = correspondencesFrameFrame.at(i).get<1>();
        const FramePtr& frame1 = correspondencesFrameFrame.at(i).get<2>();
        const FramePtr& frame2 = correspondencesFrameFrame.at(i).get<3>();

        const Eigen::Matrix4d& H_cam_odo1 = mExtrinsics.getGlobalCameraPose(cameraIdx1);
        const Eigen::Matrix4d& H_cam_odo2 = mExtrinsics.getGlobalCameraPose(cameraIdx2);

        Eigen::Matrix4d H_cam1 = frame1->odometer()->pose() * H_cam_odo1;
        Eigen::Matrix4d H_cam2 = frame2->odometer()->pose() * H_cam_odo2;

        overlay.begin(VCharge::LINES);

        switch (cameraIdx1)
        {
        case CAMERA_FRONT:
            overlay.color4f(1.0f, 0.0f, 0.0f, 0.5f);
            break;
        case CAMERA_LEFT:
            overlay.color4f(0.0f, 1.0f, 0.0f, 0.5f);
            break;
        case CAMERA_REAR:
            overlay.color4f(0.0f, 1.0f, 1.0f, 0.5f);
            break;
        case CAMERA_RIGHT:
            overlay.color4f(1.0f, 1.0f, 0.0f, 0.5f);
            break;
        default:
            overlay.color4f(1.0f, 1.0f, 1.0f, 0.5f);
        }

        overlay.vertex3f(H_cam1(0,3), H_cam1(1,3), H_cam1(2,3));

        switch (cameraIdx2)
        {
        case CAMERA_FRONT:
            overlay.color4f(1.0f, 0.0f, 0.0f, 0.5f);
            break;
        case CAMERA_LEFT:
            overlay.color4f(0.0f, 1.0f, 0.0f, 0.5f);
            break;
        case CAMERA_REAR:
            overlay.color4f(0.0f, 1.0f, 1.0f, 0.5f);
            break;
        case CAMERA_RIGHT:
            overlay.color4f(1.0f, 1.0f, 0.0f, 0.5f);
            break;
        default:
            overlay.color4f(1.0f, 1.0f, 1.0f, 0.5f);
        }

        overlay.vertex3f(H_cam2(0,3), H_cam2(1,3), H_cam2(2,3));
        overlay.end();
    }

    overlay.publish();
}

void
CameraRigBA::visualize3D3DCorrespondences(const std::string& overlayName,
                                          const std::vector<Correspondence3D3D>& correspondences) const
{
    GLOverlayExtended overlay(overlayName, VCharge::COORDINATE_FRAME_GLOBAL);

    // visualize 3D-3D correspondences
    overlay.clear();
    overlay.lineWidth(1.0f);

    overlay.begin(VCharge::LINES);

    for (size_t i = 0; i < correspondences.size(); ++i)
    {
        int cameraIdx1 = correspondences.at(i).get<0>();
        int cameraIdx2 = correspondences.at(i).get<1>();

        const FramePtr& frame1 = correspondences.at(i).get<2>();
        const FramePtr& frame2 = correspondences.at(i).get<3>();

        Eigen::Vector3d p1 = correspondences.at(i).get<4>()->point();
        Eigen::Vector3d p2 = correspondences.at(i).get<5>()->point();

        const Eigen::Matrix4d& H_cam_odo1 = mExtrinsics.getGlobalCameraPose(cameraIdx1);
        const Eigen::Matrix4d& H_cam_odo2 = mExtrinsics.getGlobalCameraPose(cameraIdx2);

        Eigen::Matrix4d H_cam1 = frame1->odometer()->pose() * H_cam_odo1;
        Eigen::Matrix4d H_cam2 = frame2->odometer()->pose() * H_cam_odo2;

        switch (cameraIdx1)
        {
        case CAMERA_FRONT:
            overlay.color4f(1.0f, 0.0f, 0.0f, 0.3f);
            break;
        case CAMERA_LEFT:
            overlay.color4f(0.0f, 1.0f, 0.0f, 0.3f);
            break;
        case CAMERA_REAR:
            overlay.color4f(0.0f, 1.0f, 1.0f, 0.3f);
            break;
        case CAMERA_RIGHT:
            overlay.color4f(1.0f, 1.0f, 0.0f, 0.3f);
            break;
        default:
            overlay.color4f(1.0f, 1.0f, 1.0f, 0.3f);
        }

        overlay.vertex3f(H_cam1(0,3), H_cam1(1,3), H_cam1(2,3));
        overlay.vertex3f(p1(0), p1(1), p1(2));

        overlay.color3f(1.0f, 1.0f, 1.0f);

        overlay.vertex3f(p1(0), p1(1), p1(2));
        overlay.vertex3f(p2(0), p2(1), p2(2));

        switch (cameraIdx2)
        {
        case CAMERA_FRONT:
            overlay.color4f(1.0f, 0.0f, 0.0f, 0.7f);
            break;
        case CAMERA_LEFT:
            overlay.color4f(0.0f, 1.0f, 0.0f, 0.7f);
            break;
        case CAMERA_REAR:
            overlay.color4f(0.0f, 1.0f, 1.0f, 0.7f);
            break;
        case CAMERA_RIGHT:
            overlay.color4f(1.0f, 1.0f, 0.0f, 0.7f);
            break;
        default:
            overlay.color4f(1.0f, 1.0f, 1.0f, 0.7f);
        }

        overlay.vertex3f(p2(0), p2(1), p2(2));
        overlay.vertex3f(H_cam2(0,3), H_cam2(1,3), H_cam2(2,3));
    }

    overlay.end();

    overlay.publish();
}

void
CameraRigBA::visualize3D3DCorrespondences(const std::string& overlayName,
                                          const std::vector<Correspondence2D2D>& correspondences2D2D) const
{
    std::vector<Correspondence3D3D> correspondences3D3D;
    correspondences3D3D.reserve(correspondences2D2D.size());

    for (size_t i = 0; i < correspondences2D2D.size(); ++i)
    {
        const Point2DFeaturePtr& p1 = correspondences2D2D.at(i).first;
        const Point2DFeaturePtr& p2 = correspondences2D2D.at(i).second;

        correspondences3D3D.push_back(boost::make_tuple(p1->frame()->cameraId(), p2->frame()->cameraId(),
                                                        p1->frame(), p2->frame(),
                                                        p1->feature3D(), p2->feature3D()));
    }

    visualize3D3DCorrespondences(overlayName, correspondences3D3D);
}

cv::Mat
CameraRigBA::buildDescriptorMat(const std::vector<Point2DFeaturePtr>& features,
                                std::vector<size_t>& indices) const
{
    for (size_t i = 0; i < features.size(); ++i)
    {
         if (features.at(i)->feature3D().get() != 0)
         {
             indices.push_back(i);
         }
    }

    cv::Mat dtor(indices.size(), features.at(0)->descriptor().cols, features.at(0)->descriptor().type());

    for (size_t i = 0; i < indices.size(); ++i)
    {
         features.at(indices.at(i))->descriptor().copyTo(dtor.row(i));
    }

    return dtor;
}

bool
CameraRigBA::project3DPoint(const CataCamera& camera,
                            const Eigen::Matrix4d& H,
                            const Eigen::Vector4d& src, Eigen::Vector3d& dst) const
{
    // transform point from world frame to camera frame
    Eigen::Vector3d P = H.block<3,3>(0,0) * (src.block<3,1>(0,0) / src(3)) + H.block<3,1>(0,3);

    // check if point is behind camera
    if (P(2) < 0.0)
    {
        return false;
    }

    camera.space2plane(P(0), P(1), P(2), &dst(0), &dst(1));
    dst(2) = 1.0;

    return true;
}

void
CameraRigBA::rectifyImagePoint(const CataCamera& camera,
                               const CataCameraParameters& cameraParameters,
                               const cv::Point2f& src, cv::Point2f& dst, double focal) const
{
    Eigen::Vector3d P;

    camera.liftProjective(src.x, src.y, &P(0), &P(1), &P(2));

    P /= P(2);

    dst.x = P(0) * focal + cameraParameters.imageWidth() / 2.0f;
    dst.y = P(1) * focal + cameraParameters.imageHeight() / 2.0f;
}

void
CameraRigBA::rectifyImagePoint(const CataCamera& camera,
                               const CataCameraParameters& cameraParameters,
                               const Eigen::Vector2d& src, Eigen::Vector2d& dst, double focal) const
{
    Eigen::Vector3d P;

    camera.liftProjective(src(0), src(1), &P(0), &P(1), &P(2));

    P /= P(2);

    Eigen::Vector2d pp(cameraParameters.imageWidth() / 2.0, cameraParameters.imageHeight() / 2.0);
    dst = P.block<2,1>(0,0) * focal + pp;
}

void
CameraRigBA::rectifyImagePoints(const CataCamera& camera,
                                const CataCameraParameters& cameraParameters,
                                const std::vector<cv::Point2f>& src,
                                std::vector<cv::Point2f>& dst,
                                double focal) const
{
    dst.resize(src.size());

    cv::Point2f pp(cameraParameters.imageWidth() / 2.0f, cameraParameters.imageHeight() / 2.0f);
    for (size_t i = 0; i < src.size(); ++i)
    {
        const cv::Point2f& p = src.at(i);

        Eigen::Vector3d P;
        camera.liftProjective(p.x, p.y, &P(0), &P(1), &P(2));

        P /= P(2);

        dst.at(i) = cv::Point2f(P(0), P(1)) * focal + pp;
    }
}

void
CameraRigBA::tvt(const CataCamera& camera,
                 const CataCameraParameters& cameraParameters,
                 const Eigen::Matrix4d& H1,
                 const std::vector<cv::Point2f>& imagePoints1,
                 const Eigen::Matrix4d& H2,
                 const std::vector<cv::Point2f>& imagePoints2,
                 const Eigen::Matrix4d& H3,
                 const std::vector<cv::Point2f>& imagePoints3,
                 std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d> >& points3D,
                 std::vector<size_t>& inliers) const
{
    Eigen::Matrix3d K;
    K << kNominalFocalLength, 0.0, cameraParameters.imageWidth() / 2.0,
         0.0, kNominalFocalLength, cameraParameters.imageHeight() / 2.0,
         0.0, 0.0, 1.0;

    Eigen::Matrix<double, 3, 4> P1 = K * H1.block<3,4>(0,0);
    Eigen::Matrix<double, 3, 4> P2 = K * H2.block<3,4>(0,0);
    Eigen::Matrix<double, 3, 4> P3 = K * H3.block<3,4>(0,0);

    Eigen::Matrix4d H12 = H2 * H1.inverse();
    Eigen::Matrix4d H23 = H3 * H2.inverse();
    Eigen::Matrix4d H13 = H3 * H1.inverse();

    Eigen::Matrix3d E12 = skew(Eigen::Vector3d(H12.block<3,1>(0,3))) * H12.block<3,3>(0,0);
    Eigen::Matrix3d E23 = skew(Eigen::Vector3d(H23.block<3,1>(0,3))) * H23.block<3,3>(0,0);
    Eigen::Matrix3d E13 = skew(Eigen::Vector3d(H13.block<3,1>(0,3))) * H13.block<3,3>(0,0);

    double focal = K(0,0);
    Eigen::Vector2d pp(K(0,2), K(1,2));

    // linear triangulation
    for (size_t i = 0; i < imagePoints1.size(); ++i)
    {
        const cv::Point2f& p1_cv = imagePoints1.at(i);
        const cv::Point2f& p2_cv = imagePoints2.at(i);
        const cv::Point2f& p3_cv = imagePoints3.at(i);

        cv::Point2f rect_p1_cv, rect_p2_cv, rect_p3_cv;
        rectifyImagePoint(camera, cameraParameters, p1_cv, rect_p1_cv, kNominalFocalLength);
        rectifyImagePoint(camera, cameraParameters, p2_cv, rect_p2_cv, kNominalFocalLength);
        rectifyImagePoint(camera, cameraParameters, p3_cv, rect_p3_cv, kNominalFocalLength);

        Eigen::Matrix4d J;
        J.row(0) = P2.row(2) * rect_p2_cv.x - P2.row(0);
        J.row(1) = P2.row(2) * rect_p2_cv.y - P2.row(1);
        J.row(2) = P3.row(2) * rect_p3_cv.x - P3.row(0);
        J.row(3) = P3.row(2) * rect_p3_cv.y - P3.row(1);

        Eigen::JacobiSVD<Eigen::MatrixXd> svd(J, Eigen::ComputeThinU | Eigen::ComputeThinV);
        Eigen::Vector4d scenePoint = svd.matrixV().block<4,1>(0,3);

        scenePoint /= scenePoint(3);

        // validate scene point
        Eigen::Vector3d p1, p2, p3;
        if (!project3DPoint(camera, H1, scenePoint, p1))
        {
            continue;
        }
        if (!project3DPoint(camera, H2, scenePoint, p2))
        {
            continue;
        }
        if (!project3DPoint(camera, H3, scenePoint, p3))
        {
            continue;
        }

        points3D.push_back(scenePoint.block<3,1>(0,0));
        inliers.push_back(i);
    }
}

void
CameraRigBA::prune(int flags, int poseType)
{
    // prune points that are too far away or behind a camera
    for (size_t i = 0; i < mCameras.size(); ++i)
    {
        Pose T_cam_odo(mExtrinsics.getGlobalCameraPose(i));

        Eigen::Matrix4d H_odo_cam = T_cam_odo.pose().inverse();

        for (size_t j = 0; j < mGraph.frameSegments(i).size(); ++j)
        {
            FrameSegment& segment = mGraph.frameSegments(i).at(j);

            for (size_t k = 0; k < segment.size(); ++k)
            {
                FramePtr& frame = segment.at(k);

                std::vector<Point2DFeaturePtr>& features2D = frame->features2D();

                Eigen::Matrix4d H_cam = Eigen::Matrix4d::Identity();
                if (frame->camera().get() != 0)
                {
                    H_cam = frame->camera()->pose();
                }

                Eigen::Matrix4d H_odo_inv = frame->odometer()->pose().inverse();

                for (size_t l = 0; l < features2D.size(); ++l)
                {
                    Point2DFeaturePtr& pf = features2D.at(l);

                    if (pf->feature3D().get() == 0)
                    {
                        continue;
                    }

                    Eigen::Vector4d P;
                    P << pf->feature3D()->point(), 1.0;

                    Eigen::Vector4d P_cam;
                    if (poseType == CAMERA)
                    {
                        P_cam = H_cam * P;
                    }
                    else
                    {
                        P_cam = (H_odo_cam * H_odo_inv) * P;
                    }

                    bool prune = false;

                    if ((flags & PRUNE_BEHIND_CAMERA) == PRUNE_BEHIND_CAMERA &&
                        P_cam(2) < 0.0)
                    {
                        prune = true;
                    }

                    if ((flags & PRUNE_FARAWAY) == PRUNE_FARAWAY &&
                        P_cam.block<3,1>(0,0).norm() > kMaxPoint3DDistance)
                    {
                        prune = true;
                    }

                    if ((flags & PRUNE_HIGH_REPROJ_ERR) == PRUNE_HIGH_REPROJ_ERR)
                    {
                        double error = 0.0;

                        if (poseType == CAMERA)
                        {
                            CameraReprojectionError reprojErr(mCameraParameters.at(i), pf->keypoint().pt.x, pf->keypoint().pt.y);

                            double residuals[2];
                            reprojErr(frame->camera()->rotationData(),
                                      frame->camera()->translationData(),
                                      pf->feature3D()->pointData(), residuals);

                            error = hypot(residuals[0], residuals[1]);
                        }
                        else
                        {
                            OdometerReprojectionError reprojErr(mCameraParameters.at(i), pf->keypoint().pt.x, pf->keypoint().pt.y);

                            double residuals[2];
                            reprojErr(T_cam_odo.rotationData(),
                                      T_cam_odo.translationData(),
                                      frame->odometer()->positionData(),
                                      frame->odometer()->yawData(),
                                      pf->feature3D()->pointData(), residuals);

                            error = hypot(residuals[0], residuals[1]);
                        }

                        if (error > kMaxReprojErr)
                        {
                            prune = true;
                        }
                    }

                    if (prune)
                    {
                        std::vector<Point2DFeaturePtr> features2D = pf->feature3D()->features2D();

                        for (size_t m = 0; m < features2D.size(); ++m)
                        {
                            features2D.at(m)->feature3D() = Point3DFeaturePtr();
                        }
                    }
                }
            }
        }
    }
}

void
CameraRigBA::optimize(int mode, bool optimizeZ, int nIterations)
{
    ceres::Problem problem;

    ceres::Solver::Options options;
    options.linear_solver_type = ceres::DENSE_SCHUR;
    options.max_num_iterations = nIterations;

    // intrinsics
    double intrinsicParams[CAMERA_COUNT][9];

    for (int i = 0; i < CAMERA_COUNT; ++i)
    {
        intrinsicParams[i][0] = mCameraParameters.at(i).xi();
        intrinsicParams[i][1] = mCameraParameters.at(i).k1();
        intrinsicParams[i][2] = mCameraParameters.at(i).k2();
        intrinsicParams[i][3] = mCameraParameters.at(i).p1();
        intrinsicParams[i][4] = mCameraParameters.at(i).p2();
        intrinsicParams[i][5] = mCameraParameters.at(i).gamma1();
        intrinsicParams[i][6] = mCameraParameters.at(i).gamma2();
        intrinsicParams[i][7] = mCameraParameters.at(i).u0();
        intrinsicParams[i][8] = mCameraParameters.at(i).v0();
    }

    // extrinsics
    std::vector<Pose, Eigen::aligned_allocator<Pose> > T_cam_odo(mCameras.size());
    for (size_t i = 0; i < mCameras.size(); ++i)
    {
        T_cam_odo.at(i) = Pose(mExtrinsics.getGlobalCameraPose(i));
    }

    boost::dynamic_bitset<> optimizeExtrinsics(mCameras.size());

    OdometerPtr odometerBegin;

    for (size_t i = 0; i < mCameras.size(); ++i)
    {
        for (size_t j = 0; j < mGraph.frameSegments(i).size(); ++j)
        {
            for (size_t k = 0; k < mGraph.frameSegments(i).at(j).size(); ++k)
            {
                FramePtr& frame = mGraph.frameSegments(i).at(j).at(k);

                std::vector<Point2DFeaturePtr>& features2D = frame->features2D();

                for (size_t l = 0; l < features2D.size(); ++l)
                {
                    Point2DFeaturePtr& feature2D = features2D.at(l);

                    if (feature2D->feature3D().get() == 0)
                    {
                        continue;
                    }

                    optimizeExtrinsics[i] = 1;

                    ceres::LossFunction* lossFunction = new ceres::CauchyLoss(1.0);

                    ceres::CostFunction* costFunction;
                    switch (mode)
                    {
                    case ODOMETER_FIXED:
                    {
                        if (optimizeZ)
                        {
                            costFunction
                                = new ceres::AutoDiffCostFunction<OdometerCameraReprojectionError, 2, 4, 3, 3>(
                                    new OdometerCameraReprojectionError(mCameraParameters.at(i),
                                                                        frame->odometer()->position(),
                                                                        frame->odometer()->yaw(),
                                                                        feature2D->keypoint().pt.x, feature2D->keypoint().pt.y,
                                                                        optimizeZ));
                        }
                        else
                        {
                            costFunction
                                = new ceres::AutoDiffCostFunction<OdometerCameraReprojectionError, 2, 4, 2, 3>(
                                    new OdometerCameraReprojectionError(mCameraParameters.at(i),
                                                                        frame->odometer()->position(),
                                                                        frame->odometer()->yaw(),
                                                                        feature2D->keypoint().pt.x, feature2D->keypoint().pt.y,
                                                                        optimizeZ));
                        }
                        break;
                    }
                    case ODOMETER_VARIABLE:
                    {
                        if (optimizeZ)
                        {
                            costFunction
                                = new ceres::AutoDiffCostFunction<OdometerReprojectionError, 2, 4, 3, 2, 1, 3>(
                                    new OdometerReprojectionError(mCameraParameters.at(i),
                                                                  feature2D->keypoint().pt.x, feature2D->keypoint().pt.y,
                                                                  optimizeZ));
                        }
                        else
                        {
                            costFunction
                                = new ceres::AutoDiffCostFunction<OdometerReprojectionError, 2, 4, 2, 2, 1, 3>(
                                    new OdometerReprojectionError(mCameraParameters.at(i),
                                                                  feature2D->keypoint().pt.x, feature2D->keypoint().pt.y,
                                                                  optimizeZ));
                        }
                        break;
                    }
                    case CATA_ODOMETER:
                    {
                        if (optimizeZ)
                        {
                            costFunction
                                = new ceres::AutoDiffCostFunction<CataOdometerReprojectionError, 2, 9, 4, 3, 2, 1, 3>(
                                    new CataOdometerReprojectionError(feature2D->keypoint().pt.x, feature2D->keypoint().pt.y,
                                                                      optimizeZ));
                        }
                        else
                        {
                            costFunction
                                = new ceres::AutoDiffCostFunction<CataOdometerReprojectionError, 2, 9, 4, 2, 2, 1, 3>(
                                    new CataOdometerReprojectionError(feature2D->keypoint().pt.x, feature2D->keypoint().pt.y,
                                                                      optimizeZ));
                        }
                        break;
                    }
                    case CAMERA:
                    {
                        costFunction
                            = new ceres::AutoDiffCostFunction<CameraReprojectionError, 2, 4, 3, 3>(
                                new CameraReprojectionError(mCameraParameters.at(i),
                                                            feature2D->keypoint().pt.x, feature2D->keypoint().pt.y));
                        break;
                    }
                    }

                    switch (mode)
                    {
                    case ODOMETER_FIXED:
                    {
                        problem.AddResidualBlock(costFunction, lossFunction,
                                                 T_cam_odo.at(i).rotationData(),
                                                 T_cam_odo.at(i).translationData(),
                                                 feature2D->feature3D()->pointData());
                        break;
                    }
                    case ODOMETER_VARIABLE:
                    {
                        problem.AddResidualBlock(costFunction, lossFunction,
                                                 T_cam_odo.at(i).rotationData(),
                                                 T_cam_odo.at(i).translationData(),
                                                 frame->odometer()->positionData(),
                                                 frame->odometer()->yawData(),
                                                 feature2D->feature3D()->pointData());
                        break;
                    }
                    case CATA_ODOMETER:
                    {
                        problem.AddResidualBlock(costFunction, lossFunction,
                                                 intrinsicParams[i],
                                                 T_cam_odo.at(i).rotationData(),
                                                 T_cam_odo.at(i).translationData(),
                                                 frame->odometer()->positionData(),
                                                 frame->odometer()->yawData(),
                                                 feature2D->feature3D()->pointData());

                        break;
                    }
                    case CAMERA:
                    {
                        problem.AddResidualBlock(costFunction, lossFunction,
                                                 frame->camera()->rotationData(),
                                                 frame->camera()->translationData(),
                                                 feature2D->feature3D()->pointData());
                        break;
                    }
                    }
                }

                switch (mode)
                {
                case ODOMETER_VARIABLE:
                case CATA_ODOMETER:
                {
                    if (odometerBegin.get() == 0)
                    {
                        odometerBegin = frame->odometer();
                    }
                    if (frame->odometer()->timeStamp() < odometerBegin->timeStamp())
                    {
                        odometerBegin = frame->odometer();
                    }

                    break;
                }
                case CAMERA:
                {
                    ceres::LocalParameterization* quaternionParameterization =
                        new ceres::QuaternionParameterization;

                    problem.SetParameterization(frame->camera()->rotationData(), quaternionParameterization);

                    break;
                }
                }
            }
        }
    }

    if (mode != CAMERA)
    {
        for (size_t i = 0; i < mCameras.size(); ++i)
        {
            if (optimizeExtrinsics[i])
            {
                ceres::LocalParameterization* quaternionParameterization =
                    new ceres::QuaternionParameterization;

                problem.SetParameterization(T_cam_odo.at(i).rotationData(), quaternionParameterization);
            }
        }
    }

    ceres::Solver::Summary summary;
    ceres::Solve(options, &problem, &summary);

    if (mVerbose)
    {
        std::cout << summary.BriefReport() << std::endl;
    }

    if (mode != CAMERA)
    {
        for (size_t i = 0; i < mCameras.size(); ++i)
        {
            mExtrinsics.setGlobalCameraPose(i, T_cam_odo.at(i).pose());
        }
    }

    if (mode == CATA_ODOMETER)
    {
        for (int i = 0; i < CAMERA_COUNT; ++i)
        {
            mCameraParameters.at(i).xi() = intrinsicParams[i][0];
            mCameraParameters.at(i).k1() = intrinsicParams[i][1];
            mCameraParameters.at(i).k2() = intrinsicParams[i][2];
            mCameraParameters.at(i).p1() = intrinsicParams[i][3];
            mCameraParameters.at(i).p2() = intrinsicParams[i][4];
            mCameraParameters.at(i).gamma1() = intrinsicParams[i][5];
            mCameraParameters.at(i).gamma2() = intrinsicParams[i][6];
            mCameraParameters.at(i).u0() = intrinsicParams[i][7];
            mCameraParameters.at(i).v0() = intrinsicParams[i][8];
        }
    }
}

void
CameraRigBA::visualize(const std::string& overlayPrefix, int type)
{
    boost::unordered_set<Odometer*> odometerSet;

    for (size_t i = 0; i < mCameras.size(); ++i)
    {
        std::ostringstream oss;
        oss << overlayPrefix << i + 1;

        GLOverlayExtended overlay(oss.str(), VCharge::COORDINATE_FRAME_GLOBAL);

        // visualize camera poses and 3D scene points
        overlay.clear();
        overlay.pointSize(2.0f);
        overlay.lineWidth(1.0f);

        // draw cameras
        std::vector<OdometerPtr> odometers;
        std::vector<PosePtr> cameras;
        std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d> > scenePoints;

        boost::unordered_set<Point3DFeature*> scenePointSet;

        std::vector<FrameSegment>& segments = mGraph.frameSegments(i);
        for (size_t j = 0; j < segments.size(); ++j)
        {
            FrameSegment& segment = segments.at(j);

            for (size_t k = 0; k < segment.size(); ++k)
            {
                if (type == ODOMETER)
                {
                    odometers.push_back(segment.at(k)->odometer());
                    odometerSet.insert(segment.at(k)->odometer().get());
                }
                else
                {
                    cameras.push_back(segment.at(k)->camera());
                }

                std::vector<Point2DFeaturePtr>& features2D = segment.at(k)->features2D();

                for (size_t l = 0; l < features2D.size(); ++l)
                {
                    if (features2D.at(l)->feature3D().get() == 0)
                    {
                        continue;
                    }

                    if (features2D.at(l)->feature3D()->point().norm() < 1000.0)
                    {
                        scenePointSet.insert(features2D.at(l)->feature3D().get());
                    }
                }
            }
        }

        if (type == ODOMETER)
        {
            for (size_t j = 0; j < odometers.size(); ++j)
            {
                OdometerPtr& odometer = odometers.at(j);

                Eigen::Matrix4d H_odo = odometer->pose();
                Eigen::Matrix4d H_cam = H_odo * mExtrinsics.getGlobalCameraPose(i);

                double xBound = 0.1;
                double yBound = 0.1;
                double zFar = 0.2;

                std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d> > frustum;
                frustum.push_back(Eigen::Vector3d(0.0, 0.0, 0.0));
                frustum.push_back(Eigen::Vector3d(-xBound, -yBound, zFar));
                frustum.push_back(Eigen::Vector3d(xBound, -yBound, zFar));
                frustum.push_back(Eigen::Vector3d(xBound, yBound, zFar));
                frustum.push_back(Eigen::Vector3d(-xBound, yBound, zFar));

                for (size_t k = 0; k < frustum.size(); ++k)
                {
                    frustum.at(k) = transformPoint(H_cam, frustum.at(k));
                }

                overlay.color4f(1.0f, 1.0f, 1.0f, 1.0f);
                overlay.begin(VCharge::LINES);

                for (int k = 1; k < 5; ++k)
                {
                    overlay.vertex3f(frustum.at(0)(0), frustum.at(0)(1), frustum.at(0)(2));
                    overlay.vertex3f(frustum.at(k)(0), frustum.at(k)(1), frustum.at(k)(2));
                }

                overlay.end();

                switch (i)
                {
                case CAMERA_FRONT:
                    overlay.color4f(1.0f, 0.0f, 0.0f, 0.5f);
                    break;
                case CAMERA_LEFT:
                    overlay.color4f(0.0f, 1.0f, 0.0f, 0.5f);
                    break;
                case CAMERA_REAR:
                    overlay.color4f(0.0f, 1.0f, 1.0f, 0.5f);
                    break;
                case CAMERA_RIGHT:
                    overlay.color4f(1.0f, 1.0f, 0.0f, 0.5f);
                    break;
                default:
                    overlay.color4f(1.0f, 1.0f, 1.0f, 0.5f);
                }

                overlay.begin(VCharge::POLYGON);

                for (int k = 1; k < 5; ++k)
                {
                    overlay.vertex3f(frustum.at(k)(0), frustum.at(k)(1), frustum.at(k)(2));
                }

                overlay.end();
            }

            overlay.lineWidth(1.0f);
            overlay.pointSize(2.0f);
        }
        else
        {
            for (size_t j = 0; j < cameras.size(); ++j)
            {
                PosePtr& camera = cameras.at(j);

                Eigen::Matrix4d H_cam = camera->pose().inverse();

                double xBound = 0.1;
                double yBound = 0.1;
                double zFar = 0.2;

                std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d> > frustum;
                frustum.push_back(Eigen::Vector3d(0.0, 0.0, 0.0));
                frustum.push_back(Eigen::Vector3d(-xBound, -yBound, zFar));
                frustum.push_back(Eigen::Vector3d(xBound, -yBound, zFar));
                frustum.push_back(Eigen::Vector3d(xBound, yBound, zFar));
                frustum.push_back(Eigen::Vector3d(-xBound, yBound, zFar));

                for (size_t k = 0; k < frustum.size(); ++k)
                {
                    frustum.at(k) = transformPoint(H_cam, frustum.at(k));
                }

                overlay.color4f(1.0f, 1.0f, 1.0f, 1.0f);
                overlay.begin(VCharge::LINES);

                for (int k = 1; k < 5; ++k)
                {
                    overlay.vertex3f(frustum.at(0)(0), frustum.at(0)(1), frustum.at(0)(2));
                    overlay.vertex3f(frustum.at(k)(0), frustum.at(k)(1), frustum.at(k)(2));
                }

                overlay.end();

                switch (i)
                {
                case CAMERA_FRONT:
                    overlay.color4f(1.0f, 0.0f, 0.0f, 0.5f);
                    break;
                case CAMERA_LEFT:
                    overlay.color4f(0.0f, 1.0f, 0.0f, 0.5f);
                    break;
                case CAMERA_REAR:
                    overlay.color4f(0.0f, 1.0f, 1.0f, 0.5f);
                    break;
                case CAMERA_RIGHT:
                    overlay.color4f(1.0f, 1.0f, 0.0f, 0.5f);
                    break;
                default:
                    overlay.color4f(1.0f, 1.0f, 1.0f, 0.5f);
                }

                overlay.begin(VCharge::POLYGON);

                for (int k = 1; k < 5; ++k)
                {
                    overlay.vertex3f(frustum.at(k)(0), frustum.at(k)(1), frustum.at(k)(2));
                }

                overlay.end();
            }
        }


        // draw 3D scene points
        switch (i)
        {
        case CAMERA_FRONT:
            overlay.color4f(1.0f, 0.0f, 0.0f, 0.5f);
            break;
        case CAMERA_LEFT:
            overlay.color4f(0.0f, 1.0f, 0.0f, 0.5f);
            break;
        case CAMERA_REAR:
            overlay.color4f(0.0f, 1.0f, 1.0f, 0.5f);
            break;
        case CAMERA_RIGHT:
            overlay.color4f(1.0f, 1.0f, 0.0f, 0.5f);
            break;
        default:
            overlay.color4f(1.0f, 1.0f, 1.0f, 0.5f);
        }

        overlay.begin(VCharge::POINTS);

        for (boost::unordered_set<Point3DFeature*>::iterator it = scenePointSet.begin();
                 it != scenePointSet.end(); ++it)
        {
            Eigen::Vector3d& p = (*it)->point();

            overlay.vertex3f(p(0), p(1), p(2));
        }

        overlay.end();

        overlay.publish();

        usleep(50000);
    }

    std::ostringstream oss;
    oss << overlayPrefix << "odo";

    GLOverlayExtended overlay(oss.str(), VCharge::COORDINATE_FRAME_GLOBAL);

    overlay.clear();
    overlay.lineWidth(1.0f);
    overlay.color3f(0.7f, 0.7f, 0.7f);

    double w_2 = 0.05;
    double l_2 = 0.1;

    double vertices[4][3] = {{-l_2, -w_2, 0.0},
                             {l_2, -w_2, 0.0},
                             {l_2, w_2, 0.0},
                             {-l_2, w_2, 0.0}};

    if (type == ODOMETER)
    {
        for (boost::unordered_set<Odometer*>::iterator it = odometerSet.begin();
                it != odometerSet.end(); ++it)
        {
            Odometer* odometer = *it;

            Eigen::Matrix4d H = odometer->pose();

            overlay.begin(VCharge::LINE_LOOP);

            for (int i = 0; i < 4; ++i)
            {
                Eigen::Vector3d p;
                p << vertices[i][0], vertices[i][1], vertices[i][2];

                p = transformPoint(H, p);

                overlay.vertex3f(p(0), p(1), p(2));
            }

            overlay.end();

            Eigen::Vector3d p0(0.0, 0.0, 0.0);
            Eigen::Vector3d p1(l_2, 0.0, 0.0);

            p0 = transformPoint(H, p0);
            p1 = transformPoint(H, p1);

            overlay.begin(VCharge::LINES);

            overlay.vertex3f(p0(0), p0(1), p0(2));
            overlay.vertex3f(p1(0), p1(1), p1(2));

            overlay.end();
        }
    }

    overlay.publish();
}

void
CameraRigBA::visualizeExtrinsics(const std::string& overlayName)
{
    GLOverlayExtended overlay(overlayName, VCharge::COORDINATE_FRAME_GLOBAL);

    // visualize extrinsics
    overlay.clear();
    overlay.lineWidth(1.0f);

    // x-axis
    overlay.color4f(1.0f, 0.0f, 0.0f, 1.0f);
    overlay.begin(VCharge::LINES);
    overlay.vertex3f(0.0f, 0.0f, 0.0f);
    overlay.vertex3f(0.3f, 0.0f, 0.0f);
    overlay.end();

    // y-axis
    overlay.color4f(0.0f, 1.0f, 0.0f, 1.0f);
    overlay.begin(VCharge::LINES);
    overlay.vertex3f(0.0f, 0.0f, 0.0f);
    overlay.vertex3f(0.0f, 0.3f, 0.0f);
    overlay.end();

    // z-axis
    overlay.color4f(0.0f, 0.0f, 1.0f, 1.0f);
    overlay.begin(VCharge::LINES);
    overlay.vertex3f(0.0f, 0.0f, 0.0f);
    overlay.vertex3f(0.0f, 0.0f, 0.3f);
    overlay.end();

    double z_ref = 0.0;
    for (int i = 0; i < CAMERA_COUNT; ++i)
    {
        Eigen::Matrix4d H_cam = mExtrinsics.getGlobalCameraPose(i);

        z_ref += H_cam(2,3);
    }
    z_ref /= CAMERA_COUNT;

    for (int i = 0; i < CAMERA_COUNT; ++i)
    {
        Eigen::Matrix4d H_cam = mExtrinsics.getGlobalCameraPose(i);

        double xBound = 0.1;
        double yBound = 0.1;
        double zFar = 0.2;

        std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d> > frustum;
        frustum.push_back(Eigen::Vector3d(0.0, 0.0, 0.0));
        frustum.push_back(Eigen::Vector3d(-xBound, -yBound, zFar));
        frustum.push_back(Eigen::Vector3d(xBound, -yBound, zFar));
        frustum.push_back(Eigen::Vector3d(xBound, yBound, zFar));
        frustum.push_back(Eigen::Vector3d(-xBound, yBound, zFar));

        for (size_t k = 0; k < frustum.size(); ++k)
        {
            frustum.at(k) = transformPoint(H_cam, frustum.at(k));
            frustum.at(k)(2) -= z_ref;
        }

        overlay.color4f(1.0f, 1.0f, 1.0f, 1.0f);
        overlay.begin(VCharge::LINES);

        for (int k = 1; k < 5; ++k)
        {
            overlay.vertex3f(frustum.at(0)(0), frustum.at(0)(1), frustum.at(0)(2));
            overlay.vertex3f(frustum.at(k)(0), frustum.at(k)(1), frustum.at(k)(2));
        }

        overlay.end();

        switch (i)
        {
        case CAMERA_FRONT:
            overlay.color4f(1.0f, 0.0f, 0.0f, 0.5f);
            break;
        case CAMERA_LEFT:
            overlay.color4f(0.0f, 1.0f, 0.0f, 0.5f);
            break;
        case CAMERA_REAR:
            overlay.color4f(0.0f, 1.0f, 1.0f, 0.5f);
            break;
        case CAMERA_RIGHT:
            overlay.color4f(1.0f, 1.0f, 0.0f, 0.5f);
            break;
        default:
            overlay.color4f(1.0f, 1.0f, 1.0f, 0.5f);
        }

        overlay.begin(VCharge::POLYGON);

        for (int k = 1; k < 5; ++k)
        {
            overlay.vertex3f(frustum.at(k)(0), frustum.at(k)(1), frustum.at(k)(2));
        }

        overlay.end();
    }

    overlay.publish();
}

bool
CameraRigBA::validateGraph(void) const
{
    bool valid = true;

    for (size_t i = 0; i < mCameras.size(); ++i)
    {
        Pose T_cam_odo(mExtrinsics.getGlobalCameraPose(i));

        for (size_t j = 0; j < mGraph.frameSegments(i).size(); ++j)
        {
            const FrameSegment& segment = mGraph.frameSegments(i).at(j);

            for (size_t k = 0; k < segment.size(); ++k)
            {
                const FramePtr& frame = segment.at(k);

                const std::vector<Point2DFeaturePtr>& features2D = frame->features2D();

                for (size_t i = 0; i < features2D.size(); ++i)
                {
                    const Point2DFeatureConstPtr& feature2D = features2D.at(i);
                    const Point3DFeatureConstPtr& feature3D = feature2D->feature3D();

                    if (feature2D->frame().get() != frame.get())
                    {
                        std::cout << "# WARNING: Container frame and parent frame do not match for 2D feature." << std::endl;
                        valid = false;
                    }

                    if (feature3D.get() == 0)
                    {
                        continue;
                    }
                }
            }
        }
    }

    return valid;
}

}
